# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://devops-special-db-svc:5432/devops_special
spring.datasource.username=postgres

# Optional: Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-prod.xml
spring.liquibase.enabled=true

