# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/devops_special
spring.datasource.username=postgres
spring.datasource.password=root

# Optional: Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-local.xml
spring.liquibase.enabled=true
